import React, { useState, useEffect } from 'react';
import axios from 'axios';
import { Search, Activity, Stethoscope, RefreshCw } from 'lucide-react';

const Dashboard = ({ renderTrigger }) => {
    const [records, setRecords] = useState([]);
    const [loading, setLoading] = useState(true);
    const [searchTerm, setSearchTerm] = useState('');

    // Specific AI CPT Query state
    const [cptQuery, setCptQuery] = useState('');
    const [cptResult, setCptResult] = useState('');
    const [loadingCpt, setLoadingCpt] = useState(false);

    const fetchRecords = async () => {
        setLoading(true);
        try {
            const response = await axios.get('http://localhost:8000/sessions');
            setRecords(response.data);
        } catch (error) {
            console.error('Failed to fetch records', error);
        } finally {
            setLoading(false);
        }
    };

    useEffect(() => {
        fetchRecords();
    }, [renderTrigger]);

    const handleCptInquiry = async () => {
        if (!cptQuery) return;
        setLoadingCpt(true);
        setCptResult('');

        try {
            const response = await axios.post(`http://localhost:8000/cpt-description?cpt_code=${cptQuery}`);
            setCptResult(response.data.description);
            // Re-fetch records to see updated arrays if we attached it to a patient
            fetchRecords();
        } catch (error) {
            setCptResult("Error: Backend LLM Service failed. Make sure Ollama/vLLM is running locally and model is downloaded.");
        } finally {
            setLoadingCpt(false);
        }
    };

    const filteredRecords = records.filter(record => {
        const term = searchTerm.toLowerCase();
        const nameMatch = record.patient_info?.name?.toLowerCase().includes(term);
        const idMatch = record._id?.toLowerCase().includes(term);
        const icdMatch = record.icd10_codes?.some(code => code.toLowerCase().includes(term));
        const cptMatch = record.cpt_codes?.some(cpt => cpt.code.toLowerCase().includes(term));

        return nameMatch || idMatch || icdMatch || cptMatch;
    });

    return (
        <div style={{ display: 'flex', flexDirection: 'column', gap: '24px' }}>

            {/* CPT AI Assistant Panel */}
            <div className="glass-panel" style={{ background: 'rgba(99, 102, 241, 0.05)', borderColor: 'rgba(99, 102, 241, 0.2)' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '16px' }}>
                    <div style={{ background: 'var(--primary)', padding: '8px', borderRadius: '8px', display: 'flex' }}>
                        <Activity color="white" size={20} />
                    </div>
                    <div>
                        <h3 style={{ margin: 0 }}>AI CPT Assistant</h3>
                        <p style={{ margin: 0, fontSize: '0.85rem' }}>Ask the local Large Language Model for code contexts.</p>
                    </div>
                </div>

                <div style={{ display: 'flex', gap: '12px' }}>
                    <input
                        type="text"
                        className="input-field"
                        placeholder="Enter CPT Code (e.g., 99213)"
                        value={cptQuery}
                        onChange={(e) => setCptQuery(e.target.value)}
                        style={{ margin: 0 }}
                    />
                    <button className="btn btn-primary" onClick={handleCptInquiry} disabled={loadingCpt || !cptQuery}>
                        {loadingCpt ? <RefreshCw size={18} className="spinner" /> : 'Analyze'}
                    </button>
                </div>

                {cptResult && (
                    <div style={{ marginTop: '16px', padding: '16px', background: 'rgba(0,0,0,0.3)', borderRadius: '8px', fontSize: '0.9rem', lineHeight: '1.6' }}>
                        <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '8px', color: 'var(--primary)' }}>
                            <Stethoscope size={16} />
                            <span style={{ fontWeight: 600 }}>Medical Context generated by AI:</span>
                        </div>
                        {cptResult}
                    </div>
                )}
            </div>

            {/* Patient Database Panel */}
            <div className="glass-panel">
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '24px' }}>
                    <h2 style={{ margin: 0 }}>Patient Database</h2>
                    <div style={{ position: 'relative', width: '300px' }}>
                        <Search size={18} style={{ position: 'absolute', left: '12px', top: '50%', transform: 'translateY(-50%)', color: 'var(--text-secondary)' }} />
                        <input
                            type="text"
                            className="input-field"
                            placeholder="Search by Name, ICD, CPT..."
                            style={{ paddingLeft: '40px', margin: 0 }}
                            value={searchTerm}
                            onChange={(e) => setSearchTerm(e.target.value)}
                        />
                    </div>
                </div>

                {loading ? (
                    <div style={{ textAlign: 'center', padding: '40px', color: 'var(--text-secondary)' }}>
                        <RefreshCw size={32} className="spinner" style={{ marginBottom: '16px' }} />
                        <p>Loading patient records from MongoDB...</p>
                    </div>
                ) : filteredRecords.length === 0 ? (
                    <div style={{ textAlign: 'center', padding: '40px', color: 'var(--text-secondary)', background: 'rgba(0,0,0,0.1)', borderRadius: '8px' }}>
                        <p>No matching patient records found.</p>
                    </div>
                ) : (
                    <div className="data-table-container">
                        <table className="data-table">
                            <thead>
                                <tr>
                                    <th>Patient Name</th>
                                    <th>DOB</th>
                                    <th>ICD-10 Diagnoses</th>
                                    <th>Inferred AI Context</th>
                                </tr>
                            </thead>
                            <tbody>
                                {filteredRecords.map(record => (
                                    <tr key={record._id}>
                                        <td style={{ fontWeight: 500, color: 'white' }}>{record.patient_info?.name || 'Unknown'}</td>
                                        <td>{record.patient_info?.dob || 'Unknown'}</td>
                                        <td>
                                            <div style={{ display: 'flex', flexWrap: 'wrap', gap: '6px' }}>
                                                {record.icd10_codes?.map(code => (
                                                    <span key={code} className="badge">{code}</span>
                                                )) || <span style={{ color: 'var(--text-secondary)', fontSize: '0.85rem' }}>None recorded</span>}
                                            </div>
                                        </td>
                                        <td>
                                            <div style={{ display: 'flex', flexWrap: 'wrap', gap: '6px' }}>
                                                {record.cpt_codes?.map(cpt => (
                                                    <span key={cpt.code} className="badge blue" title={cpt.description}>{cpt.code}</span>
                                                )) || <span style={{ color: 'var(--text-secondary)', fontSize: '0.85rem' }}>No AI Analysis yet</span>}
                                            </div>
                                        </td>
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                    </div>
                )}
            </div>

        </div>
    );
};

export default Dashboard;
